workout-app:
  replicaCount: 1
  resources:
    requests:
      cpu: 150m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  fullnameOverride: backend
  image:
    repository: 273809175099.dkr.ecr.ap-south-1.amazonaws.com/dev_protfolio
    tag: backend-v1.0.1
    pullPolicy: IfNotPresent
  service:
    port: 8000
  env:
    MONGO_URI: mongodb://workout:workoutpass123@mongodb-replica-set-svc:27017/workouts?authSource=admin&replicaSet=mongodb-replica-set
    LOG_LEVEL: info
workout-frontend:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  fullnameOverride: frontend
  image:
    repository: 273809175099.dkr.ecr.ap-south-1.amazonaws.com/dev_protfolio
    tag: frontend-v1.0.1
    pullPolicy: IfNotPresent
  service:
    port: 80
