workout-app:
  replicaCount: 2
  resources:
    requests:
      cpu: 150m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  fullnameOverride: backend
  image:
    repository: us-central1-docker.pkg.dev/porfolio-480111/workout-backend
    tag: v0.1.0
    pullPolicy: IfNotPresent
  service:
    port: 8000
  env:
    MONGO_URI: mongodb://workout:workoutpass123@mongodb-replica-set-svc:27017/workouts?authSource=admin&replicaSet=mongodb-replica-set
    LOG_LEVEL: info
workout-frontend:
  replicaCount: 2
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  fullnameOverride: frontend
  image:
    repository: us-central1-docker.pkg.dev/porfolio-480111/workout-frontend
    tag: v0.1.0
    pullPolicy: IfNotPresent
  service:
    port: 80
